### ISSUE TITLE
.get() raising an error is not pythonic

### ISSUE THREAD

**Issue by mapleoin** [jlafon/PynamoDB#87]
I was surprised that calling `.get()` on a model could raise a `DoesNotExist` error. Given that PynamoDB is advertised as *pythonic* I would expect a `get` method to return `None` when the item does not exist (and support an optional parameter to return instead of `None`).

**Comment by jlafon** [comment]
Hi there, please allow me to explain. I believe that the Pythonic thing to do is to raise an exception. The [Zen of Python](https://www.python.org/dev/peps/pep-0020/) says:

> Explicit is better than implicit
> Errors should never pass silently.
> Unless explicitly silenced.

But that's not the only reason an exception is raised. Suppose that ``None`` was returned instead of an exception being raised. Why was ``None`` returned? Did the connection fail? Was there a time out? Was the request not authorized? Did Amazon throttle it? If we simply return ``None`` then we have *no* way to distinguish an item's non-existence from actual failures. But if we raise ``DoesNotExist`` then we are explicitly telling the caller what happened, and the caller can catch the exception and handle it separately from other errors that may occur.

**Comment by mapleoin** [comment]
I agree with you that the method to retrieve an item from a cloud store should be able to raise multiple types of exceptions.

I don't agree that, in python, this method should be named `get`. `.get()` usually returns `None` in python's stdlib and most commonly used libraries that I've come across (notable examples include SQLAlchemy and pyredis). That creates an expectation in the user's mind. Had it been named, say, `get_item` there would be no confusion.
